/**
 * GitHub issue formatter — converts classification entries into issue objects.
 * Pure formatter with no I/O — fully testable without auth.
 */

import type { ClassificationEntry } from './classifier.js'

/** A formatted GitHub issue ready for creation or dry-run output. */
export interface FormattedIssue {
  title: string
  body: string
  labels: string[]
}

/**
 * Format classification entries into GitHub issue objects.
 * Each classification becomes one issue with title, markdown body, and labels.
 */
export function formatIssues(entries: ClassificationEntry[]): FormattedIssue[] {
  return entries.map((entry) => ({
    title: `[bettermcp] ${entry.severity.toUpperCase()}: ${entry.description}`,
    body: formatIssueBody(entry),
    labels: buildLabels(entry),
  }))
}

function formatIssueBody(entry: ClassificationEntry): string {
  const lines: string[] = []

  lines.push(`## ${entry.description}`)
  lines.push('')
  lines.push(`**Category:** \`${entry.category}\``)
  lines.push(`**Severity:** ${entry.severity}`)
  lines.push(`**Confidence:** ${(entry.confidence * 100).toFixed(0)}%`)
  lines.push(`**Observations:** ${entry.observationCount}`)
  lines.push(`**Source:** ${entry.provenance.join(', ')}`)
  lines.push('')
  lines.push('### Affected Endpoints')
  lines.push('')
  for (const ep of entry.endpoints) {
    lines.push(`- \`${ep}\``)
  }
  lines.push('')
  lines.push('### Timeline')
  lines.push('')
  lines.push(`- **First seen:** ${entry.firstSeen}`)
  lines.push(`- **Last seen:** ${entry.lastSeen}`)
  lines.push('')
  lines.push('---')
  lines.push('*Generated by [bettermcp](https://github.com/anthropics/bettermcp) triage*')

  return lines.join('\n')
}

function buildLabels(entry: ClassificationEntry): string[] {
  const labels: string[] = ['bettermcp']

  labels.push(`severity:${entry.severity}`)
  labels.push(`category:${entry.category}`)

  return labels
}

/**
 * Format issues as dry-run text output for when GitHub auth is unavailable.
 */
export function formatDryRun(issues: FormattedIssue[]): string {
  if (issues.length === 0) {
    return 'No issues to create — no classifications in the triage report.\n'
  }

  const lines: string[] = []

  lines.push('GitHub Issue Dry Run')
  lines.push('═'.repeat(40))
  lines.push('')
  lines.push(`${issues.length} issue(s) would be created:`)
  lines.push('')

  for (let i = 0; i < issues.length; i++) {
    const issue = issues[i]!
    lines.push(`── Issue ${i + 1} ${'─'.repeat(30)}`)
    lines.push(`Title: ${issue.title}`)
    lines.push(`Labels: ${issue.labels.join(', ')}`)
    lines.push('')
    lines.push(issue.body)
    lines.push('')
  }

  lines.push('To create these issues, configure GitHub access:')
  lines.push('  1. Install the GitHub CLI: https://cli.github.com')
  lines.push('  2. Authenticate: gh auth login')
  lines.push('  3. Run: npx bettermcp triage --github')
  lines.push('')

  return lines.join('\n')
}
